# Generated by Django 3.2.4 on 2021-07-11 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0003_alter_zone_city'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspector',
            name='zone',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='election.zone'),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='zone',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='election.zone'),
        ),
    ]
