# Generated by Django 3.2.4 on 2021-07-16 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210716_0144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspector',
            name='election',
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='election',
        ),
    ]
