# Generated by Django 3.2.4 on 2021-07-10 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0002_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.city'),
        ),
    ]
